### ISSUE TITLE
Design Jupyter T-shirts

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/design#13]
@cameronoelsen is going to also design us Jupyter T-shirts!

**Comment by rgbkrk** [comment]
Any way of making one that's just the "jupyter" name (with the right font) centered on a shirt, but no logo?

**Comment by ellisonbg** [comment]
I like this idea - @cameronoelsen can this be one of your prototypes?

On Mon, Jun 15, 2015 at 1:30 PM, Kyle Kelley <notifications@github.com>
wrote:

> Any way of making one that's just the "jupyter" name (with the right font)
> centered on a shirt, but no logo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/13#issuecomment-112199047>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
But @rgbkrk - I will also have @cameronoelsen do a special one for you that is just chompy with no words ;-)

**Comment by rgbkrk** [comment]
> do a special one for you that is just chompy with no words ;-)

![._.](http://media3.giphy.com/media/13AbwdfEHTvih2/giphy.gif)

**Comment by Carreau** [comment]
Do you think we should have slightly differents T-shirs for significant contributors/evangelist, that basically are higher quality + their name (and/or role) on sleeves / front ?

**Comment by ellisonbg** [comment]
We could definitely explore something like that. Although having individual
names on the shirt might get expensive. But having a different t-shirt for
"core devs" would be a good idea.

On Mon, Jun 15, 2015 at 2:20 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Do you think we should have slightly differents T-shirs for significant
> contributors/evangelist, that basically are higher quality + their name
> (and/or role) on sleeves / front ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/13#issuecomment-112215329>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Could I request that we make some t-shirts in women's sizes/cuts? I don't think this would actually change anything about the design itself, but then again, I don't know anything about t-shirt design, so I thought I'd mention it now :-)

**Comment by Carreau** [comment]
We'll need a model to test the size-cut. Are you a volunteer ?

**Comment by ellisonbg** [comment]
We can and should definitely do that!

On Mon, Jun 15, 2015 at 3:13 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> We'll need a model to test the size-cut. Are you a volunteer ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/13#issuecomment-112225351>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> We can and should definitely do that!
> On Mon, Jun 15, 2015 at 3:13 PM, Matthias Bussonnier wrote:
> > We'll need a model to test the size-cut. Are you a volunteer ?

Well I'm not sure if Brian is enthusiast about you being a model, or doing woman-cuts & size. 
Or maybe he is volonteering to be the model ?

Do we try to make T-Shirt for SciPy ? If so should we contact organizer to know the men/women ratio ?

**Comment by ivanov** [comment]
We all agree we should have t-shirts: but what color will they be?

Here are two websites that should help us with this:

http://bikeshed.org/
http://colorbrewer2.org/

**Comment by rgbkrk** [comment]
Pretty sure black is the only color of shirt for the tech community.

![](https://quotesaga.s3.amazonaws.com/quote/QS_e51a2c5c06234883bd048870cdc157ca.jpg)

**Comment by cameronoelsen** [comment]
I was thinking a darker charcoal gray (nearing black ;) )

**Comment by cameronoelsen** [comment]
Here is my first rendering of what the t-shirt may look like. 
![front_design](https://cloud.githubusercontent.com/assets/6437976/8173069/450c5eba-137d-11e5-8d31-9267615f0076.png)
![back_design](https://cloud.githubusercontent.com/assets/6437976/8173070/4699e50e-137d-11e5-87bd-00e6913f0c8f.png)

**Comment by minrk** [comment]
We should ask the Julia folks what their thoughts are on a monochrome rendering of their logo.

**Comment by takluyver** [comment]
I wonder if the top row of the logo grid should be Julia, Python, R as a reference to that source of the name.

I might also make a bigger difference between the core developer shirt and the one we sell, like a different base colour. But I'm not sure which colours, and I could be persuaded out of that.

We should also probably be careful wikth the '44 languages' claim. There are 44 *kernels* currently listed on our wiki, but there are languages that have more than one kernel (e.g. Lua), languages where the kernel is so primitive we probably don't want to claim support (e.g. Go), and grey areas like Octave/Scilab/Matlab, and Python/Brython/Skulpt/VPython - are these different languages, or different implementations of a language?

**Comment by ellisonbg** [comment]
Yeah, we are going to make a pass at reorganizing the kernel logos. Also,
there are a number of logos there for relatively obscure languages that
probably don't make sense to put in a context like this...

On Mon, Jun 15, 2015 at 5:03 PM, Thomas Kluyver <notifications@github.com>
wrote:

> I wonder if the top row of the logo grid should be Julia, Python, R as a
> reference to that source of the name.
>
> I might also make a bigger difference between the core developer shirt and
> the one we sell, like a different base colour. But I'm not sure which
> colours, and I could be persuaded out of that.
>
> We should also probably be careful wikth the '44 languages' claim. There
> are 44 *kernels* currently listed on our wiki, but there are languages
> that have more than one kernel (e.g. Lua), languages where the kernel is so
> primitive we probably don't want to claim support (e.g. Go), and grey areas
> like Octave/Scilab/Matlab, and Python/Brython/Skulpt/VPython - are these
> different languages, or different implementations of a language?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/13#issuecomment-112241327>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by damianavila** [comment]
> Pretty sure black is the only color of shirt for the tech community.

Jaja... it could be... but other colors could work to, probably the antithesis: white

> I wonder if the top row of the logo grid should be Julia, Python, R as a reference to that source of the name.

I think is a good idea...

> I might also make a bigger difference between the core developer shirt and the one we sell, like a different base colour. But I'm not sure which colours, and I could be persuaded out of that.

I also agree... a different color usually works well....

> We should also probably be careful wikth the '44 languages' claim.

Also in agreement...

**Comment by Carreau** [comment]
The logo are just in the order, and the one I threw on the mani jupyter.org main page, without really thinking at order/different implementation. 

Something disturb me in the front of the t shirt, I'm not quite sure why. I think it's an impression of imbalance left/right. But I overall like it.

The dev/classic difference can be black/white vs white/black.

**Comment by rgbkrk** [comment]
My preference here is to keep it simple.

### FRONT

jupyter

### BACK

jupyter.org

## Alternative

### FRONT

jupyter

### BACK

try.jupyter.org

**Comment by bigzachattack** [comment]
It would be nice if polos and t-shirts are available for users to buy/ I prefer polos over t-shirts, but I understand the reasoning for restricting the polos to developers.

**Comment by takluyver** [comment]
I don't think we were exactly planning to *restrict* polos to developers - I think it's fine to have a polo option available to the public as well, even if the design for that is done a bit later. We could offer all kinds of apparel. :-)

**Comment by cameronoelsen** [comment]
Hey all! Thanks for your ideas and criticisms, really appreciate to make better designs. I have attached many different layouts below with their white counterparts (in case we want to make two colors) as well as some possible polo designs at the bottom.
![layout 1](https://cloud.githubusercontent.com/assets/6437976/8196666/0279f050-1443-11e5-8ad5-ef2a68f7fdbf.png)
![layout 1a](https://cloud.githubusercontent.com/assets/6437976/8196667/074885a6-1443-11e5-883a-9ee550992ded.png)
![layout 2](https://cloud.githubusercontent.com/assets/6437976/8196670/0b236b6e-1443-11e5-9d01-1c99892a9f29.png)
![layout 2a](https://cloud.githubusercontent.com/assets/6437976/8196673/0ec189e0-1443-11e5-9806-361a54376e0f.png)
![layout 3](https://cloud.githubusercontent.com/assets/6437976/8196675/1193955a-1443-11e5-9554-d9ed8fd55aad.png)
![layout 3a](https://cloud.githubusercontent.com/assets/6437976/8196677/140999d8-1443-11e5-94e3-c4d8b13d8265.png)
![layout 4](https://cloud.githubusercontent.com/assets/6437976/8196678/1659c37a-1443-11e5-8e79-f625e92db291.png)
![layout 4a](https://cloud.githubusercontent.com/assets/6437976/8196681/18f05770-1443-11e5-944c-d2104b44f719.png)
![polo 1](https://cloud.githubusercontent.com/assets/6437976/8196685/1c4685c0-1443-11e5-9a55-f6b5828baab1.png)
![polo 2](https://cloud.githubusercontent.com/assets/6437976/8196686/1eda6f2c-1443-11e5-9c99-da3e6b756e12.png)

**Comment by rgbkrk** [comment]
What would you think about putting the URLs higher on the back?

**Comment by damianavila** [comment]
I really like the big logo at the center (picture 1 and 2)

**Comment by minrk** [comment]
- For polo: I like text inside the logo.
- I don't have a strong preference for the t-shirt logo.
- I like the idea of pointing people straight to try.jupyter.org, but it's not as easy as it should be to get back to jupyter.org once you are in tmpnb.
- I'd shy away from the claim of '44' languages, since there is lots of overlap (several Python and Javascript kernels, for instance). Perhaps something more vague, like '...and many more'
- I like the look of the url on the back a bit better than the logos, but no strong preference.
- I like the idea of the back logos, since it communicates actual information (we support lots of languages) but I don't have a good sense of how to pick which ones. I'd be fine with the ones on there now, though.

**Comment by rgbkrk** [comment]
> try.jupyter.org, but it's not as easy as it should be to get back to jupyter.org once you are in tmpnb

We really should change that.

**Comment by minrk** [comment]
Yup. It can be done with content in the Welcome notebook. I'm not sure there's room to put it anywhere permanent, like the header.

**Comment by fperez** [comment]
I know we're super pressed for time to get the order in time for scipy, sorry I was in a net blackout while traveling for the last 48h and didn't comment before.

Given the time pressure, allow me to cast my vote with some BDFL weight behind it, and we use this for the Scipy print run.  If it turns out everyone *hates* my decision, we can reconsider and revisit for future print runs.  I'm not too worried here, since this is just a t-shirt, our first, and  a limited run, so screwing up here as BDFL will have a limited impact :)

Let me also thank everyone for the fantastic job on these designs. I love it!!

My proposal (speaking only of t-shirt, not polo):

- Dark background.

- Print both fronts:
   * 50%  of them with logo that uses word next to the figure
   * 50% of them with the logo that has the word inside the figure.

That way we have two "editions", and people can pick which one they like more (a few lucky ones will collect both). Just like Alpinist did [two](http://www.needlesports.com/imagecache/0fceb95d-7015-4e18-a0af-a4b300a114d3_750x750.jpg)  [covers](http://covers.magazine-agent.com/images/image.aspx?i=10RY&w=300) for their 50th issue, we can have two.

- For the back, use simply `jupyter.org`. 

While at first I very much loved the language grid, it gradually started feeling way too much like the sponsorship t-shirt of a race or triathlon... I started looking for the Gatorade and Clif Bar logos in there... I think if we want these to be t-shirts that have more "wearability", a simpler design with fewer visual clutter will help.

As for why not `try.jupyter`, it's because it pushes people directly into a place that can be a bit weird without context. Whereas the main website has the try.jupyter button very nicely labeled, but it explains what it does well, making it a better experience.

So that's both my summary of decisions and rationale for them.  Let's make this order, and let's see how we like them!

Again, thanks everyone!!

**Comment by fperez** [comment]
ps - let's not forget to order proper women's cuts.

**Comment by ellisonbg** [comment]
Thanks Fernando I will get these ordered (with proper women's cuts).

Cheers,

Brian

On Thu, Jun 18, 2015 at 7:56 PM, Fernando Perez <notifications@github.com>
wrote:

> ps - let's not forget to order proper women's cuts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/13#issuecomment-113350635>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Here is the information about what we are purchasing. We got the ratios of T-shirt sizes from the SciPy organizers:

* Using CustomInk, with `project.jupyter@gmail.com` for the email address.
* Mens: 10 S, 30 M, 30 L, 10 XL, 5 XXL, Gildan Soft Jersey.
* Womens: 25 S, 40 M, 25 L, 5 XL, Anvil Ladies Jersey.
* ~100 each of two designs, charcoal color.

**Comment by Carreau** [comment]
Will it be delivered in Berkeley, Cal Poly ? or Austin ?

**Comment by ellisonbg** [comment]
I am going to have them delivered directly to Austin (the hotel under our names)...

**Comment by ellisonbg** [comment]
Sorry, I typed the womens numbers incorrectly. Here is the exact numbers I ordered:

Item 1: Anvil Ladies Jersey T-shirt - Charcoal
Quantity: S: 5, M: 10, L: 5, XL: 3; Total: 23

Item 2: Gildan Softstyle Jersey T-shirt - Charcoal
Quantity: S: 10, M: 30, L: 30, XL: 10, XXL: 5; Total: 85

The Mens/Womens split is based on the actual attendance numbers of SciPy.

**Comment by ellisonbg** [comment]
Also, here are the raw size numbers from the SciPy attendees to help with future orders:

![unnamed](https://cloud.githubusercontent.com/assets/27600/8295865/b1a703d8-18fd-11e5-974a-0b693d967fda.png)

**Comment by josiahdavis** [comment]
Is it possible to get these anywhere online?

**Comment by jenyquist** [comment]
I second Josiah's question.  Can we get these shirts online?

**Comment by Carreau** [comment]
We're discussing setting up a [cafepress](http://www.cafepress.com/) or similar. 

There a few questions we need to clarify first, including legal ones as most of us are funded by a non-profit, we have to be extra-careful in setting this up, even if we put a $0 commission cost on swag.

**Comment by jenyquist** [comment]
Understood, thanks.  Classy looking shirts, though, so I'll just have to
sit here green with envy until you get it sorted out.  Maybe you can have
the specifications saved at cafepress and interested parties can just
design their own directly using your template?  That way you're not a
vendor.

**Comment by Carreau** [comment]
> Maybe you can have
> the specifications saved at cafepress and interested parties can just
> design their own directly using your template?  That way you're not a
> vendor.

I am not a lawyer, and even if we are open source, I don't know how that affect the Jupyter brand. 

There have been a increase of requests these days and we are out of the T-shirts we ordered at SciPy last year, so I'll try to push that forward.

**Comment by jenyquist** [comment]
Another possibility is giving out T-shirts to donors.  Public radio does
this sort of thing all the time and they are non-profit.  Probably do have
to ask
the lawyers...
