### ISSUE TITLE
Unified technical diagrams

### ISSUE THREAD

**Issue by jdfreder** [jupyter/design#17]
I had a discussion with @ellisonbg about diagram design the other day and he suggested we come up with a unified technical diagram style, and that we ask @cameronoelsen to investigate for us.  This discussion serves that purpose.

Next week, @Carreau @takluyver and I will be giving a talk at SciPy.  I've chosen a simple diagram to start the discussion.  Eventually I'd like to be able to animate the diagrams, but I don't think that's absolutely required right now.

Summary of needs:
- Consistent diagram styling scheme (colors, shapes, lines, widths, fonts, etc).
- Animated diagrams

Example diagram:
![capture](https://cloud.githubusercontent.com/assets/3292874/8413923/f9c219d2-1e48-11e5-84a8-ec12318f0f5e.PNG)

It's important to state, the lines, shapes, and positioning I use in my sketch above can all be changed.  Also the text "send" and "receive" can be omitted if it's clearer.

**Comment by takluyver** [comment]
I drew some simple block-and-arrow diagrams which live here:

http://ipython.org/ipython-doc/3/development/how_ipython_works.html

And one of the comm+widget architecture for a talk:

https://github.com/takluyver/ipython-sfpython-feb-2015/blob/master/widget_architecture.svg

They're not works of art, but if they can be a starting point, I'd be happy.

**Comment by minrk** [comment]
And I've made a number of zmq socket diagrams like [this](https://github.com/ipython/ipython/blob/3.x/docs/source/development/figs/allconnections.svg).

**Comment by ellisonbg** [comment]
@cameronoelsen can you start to look at creating a unified design language for our diagrams based on the existing work that others have linked to? You can create a new folder in the design dropbox for this stuff.

**Comment by jdfreder** [comment]
More examples of diagrams

One I've done here:
https://cloud.githubusercontent.com/assets/3292874/7822986/f5dba636-03ad-11e5-8de4-8d559bd46acb.png

One @ellisonbg has done here:
https://rawgit.com/ipython/ipython-in-depth/master/examples/Interactive%20Widgets/images/WidgetModelView.png

As you can see, we all use completely different styles for our diagrams right now.

**Comment by takluyver** [comment]
For the record, I don't think we need to impose a single style for all block+arrow diagrams we do: we're different people, talking about different things at different levels in different ways (with different accents!). Having different diagrams reflects that.

Of course, if there are several diagrams that involve related concepts in one document/presentation, it's useful to have consistent styling within that to help people make connections.

**Comment by minrk** [comment]
Sure, it's not like we need to be strict about it. But it would probably be good to have a few official diagrams for some of the most common things, rather than the higgledy-piggledy assortment we have now.

**Comment by ellisonbg** [comment]
I think our ability to communicate effectively as a project would be
greatly helped by having a single style that is professionally designed.
Sure, we are different people, but one project, one architecture, etc.
While there are differences in how each of us talks about the project, and
the content of the presentations we give, I don't think those differences
are best expressed in the differences in visual style of our diagrams.

Plus, I think it is a waste of time for our coders to spend time
reinventing diagrams we all use when we have a designer. Although I do know
that some of us like to do these things sometimes, and am fine with any of
us customizing things on top of the basic styles we have.

From the time perspective, I think one of the benefits of having a designer
is that we can offload this type of work to them - even the diagram
creation side of things.



On Mon, Jun 29, 2015 at 11:47 AM, Thomas Kluyver <notifications@github.com>
wrote:

> For the record, I don't think we need to impose a single style for all
> block+arrow diagrams we do: we're different people, talking about different
> things at different levels in different ways (with different accents!).
> Having different diagrams reflects that.
>
> Of course, if there are several diagrams that involve related concepts in
> one document/presentation, it's useful to have consistent styling within
> that to help people make connections.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/17#issuecomment-116794172>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
![test](https://cloud.githubusercontent.com/assets/6437976/8417602/7e7f02c0-1e62-11e5-8f7e-3584455a81ec.png)
![test2](https://cloud.githubusercontent.com/assets/6437976/8417604/80a512e2-1e62-11e5-8937-127bd07fd502.png)
![variation 2](https://cloud.githubusercontent.com/assets/6437976/8417608/837b3942-1e62-11e5-80fc-51318f590bbd.png)
![variation 3](https://cloud.githubusercontent.com/assets/6437976/8417610/8596624c-1e62-11e5-83f6-682d35700f2d.png)

**Comment by cameronoelsen** [comment]
Those are four mockups that we were wondering on getting some feedback on.

**Comment by jdfreder** [comment]
Repeating my feedback for everyone to see and adding some questions for cameron:
- For this particular diagram, I prefer the kernel, server, and front-end squares to be aligned because I feel that raising the webserver incorrectly conveys that the webserver is more important.
- I dislike that the orange gradient is so significant.
- I prefer the circle-less labels for the connecting lines.
- I like the dotted line used here, signifying a different type of relationship than the solid line.
- If there are more than two "layers" or logical groups in the diagram, how do we choose the color of the 3rd, 4th, etc layers?  Is the color palette all colors between too?
- What does this look like without gradients?

**Comment by cameronoelsen** [comment]
Here is what the design looks like flat along with more buttons that work with the palette. We can make up to 10 buttons using the palette I have.
![iteration 1](https://cloud.githubusercontent.com/assets/6437976/8418188/48f97b4a-1e66-11e5-9e52-c87a286845e1.png)

**Comment by jdfreder** [comment]
^ I really like the flexibility of having up to 10 different groups.  The 5 (did I count the colors right?) that you have there look great to me.  I like the cool colors.

**Comment by minrk** [comment]
It's important to take into account that much of the time we are using these diagrams, they will be presented on extremely low-contrast projectors. That means light colors, such as the yellow and lightest blue in the last one are likely to be difficult to see in those contexts. Just something to keep in mind.

**Comment by jdfreder** [comment]
That's a really good point.  @cameronoelsen you can use the projector in the room that you're in to make sure the colors are distinguishable.

**Comment by cameronoelsen** [comment]
This is what I compiled for the Blue color scheme for use in technical documentation. We can still change the color scheme though, this is just for its current standing.
![technical diagram resources](https://cloud.githubusercontent.com/assets/6437976/8420305/d23a39c6-1e75-11e5-8ea2-6f252cc6b79c.png)

**Comment by jdfreder** [comment]
What about the line widths in the current design?  The light dashed, dotted, and solid?

**Comment by cameronoelsen** [comment]
Here is the diagram with the lines included :)
![technical diagram resources](https://cloud.githubusercontent.com/assets/6437976/8420607/0c3342a0-1e79-11e5-956a-f728e39f267d.png)

**Comment by ellisonbg** [comment]
Nice, how did you make the design spec?

On Mon, Jun 29, 2015 at 4:08 PM, Cameron Oelsen <notifications@github.com>
wrote:

> Here is the diagram with the lines included :)
> [image: technical diagram resources]
> <https://cloud.githubusercontent.com/assets/6437976/8420607/0c3342a0-1e79-11e5-956a-f728e39f267d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/17#issuecomment-116875970>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
@ellisonbg I put it together in Sketch ☺️

**Comment by jdfreder** [comment]
@cameronoelsen the specs you posted above have a mistake, the grey dashed separator line is actually '#d0d0d0', not '#5597AD` which is another blue.

**Comment by cameronoelsen** [comment]
Good catch!
![tech-diagram0resources](https://cloud.githubusercontent.com/assets/6437976/8461499/034a33fa-1fe2-11e5-982a-c1ecf94326bf.png)

**Comment by jdfreder** [comment]
@cameronoelsen a couple problems from a tutorial given at SciPy (as predicted by @minrk):

1. The separator is invisible when projected, unless you are <6ft from the screen.
2. Unfortunately, the font weight is nearly illegible from a distance too.  Does it look ugly when thicker?  And if so, is there a way to mitigate the ugliness?

**Comment by minrk** [comment]
We definitely can't use Helvetica Neue Light in figures. We might use Myriad Pro, since that's already the logo font, and the weight needs to be at least regular, and perhaps semi-bold.

**Comment by ellisonbg** [comment]
Yep

On Thu, Jul 16, 2015 at 10:28 PM, Min RK <notifications@github.com> wrote:

> We definitely can't use Helvetica Neue Light in figures. We might use
> Myriad Pro, since that's already the logo font, and the weight needs to be
> at least regular, and perhaps semi-bold.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/17#issuecomment-122179052>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Any problem with standard Helvetica?  I found it on my Windows 7 install, without me explicitly installing it.

**Comment by jdfreder** [comment]
(not that I prefer Helvetica, maybe @cameronoelsen does though)

**Comment by ellisonbg** [comment]
I think a heavier weight of Helvetica would be fine, but there may be
other, better fonts for this.

On Fri, Jul 17, 2015 at 9:28 AM, Jonathan Frederic <notifications@github.com
> wrote:

> (not that I prefer Helvetica, maybe @cameronoelsen
> <https://github.com/cameronoelsen> does though)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/17#issuecomment-122333335>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
One advantage of Helvetica Neue or Myriad Pro is the availability of a semibold/medium weight. I'm not aware of a medium weight Helvetica. I'm not opposed in principle to Helvetica Neue, just the light weight.

**Comment by rgbkrk** [comment]
Wow these are great.

Do we have Myriad Pro available somewhere?

**Comment by ellisonbg** [comment]
We have a Typekit account that has it, but that doesn't help for desktop
usage. I think you can hook up typekit to Adobe Creative Suite to get the
fonts on your desktop, but I haven't figured that out yet.

We should look at getting a project wide subscription for this...

On Fri, Jul 17, 2015 at 2:27 PM, Kyle Kelley <notifications@github.com>
wrote:

> Wow these are great.
>
> Do we have Myriad Pro available somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/17#issuecomment-122422446>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
