### ISSUE TITLE
JupyterDay logos

### ISSUE THREAD

**Issue by cameronoelsen** [jupyter/design#19]
So I made a few different designs for the JupyterDay logo and narrowed it down to these two. I really like the first logo more-so than the second because of the reference to a pin (location). The second logo was more focused on the content of the event. I would love feedback on which is your favorite!

![jupyterday](https://cloud.githubusercontent.com/assets/6437976/10498966/6f5201fc-7282-11e5-922b-aab126b6e87f.png)
![jupyterday2](https://cloud.githubusercontent.com/assets/6437976/10498971/7182350a-7282-11e5-8837-1266510ddf6c.png)

**Comment by rgbkrk** [comment]
The geographic pinpoint motif is nice!

**Comment by minrk** [comment]
With the pinpoint, I don't think any resemblance to a planet remains. Not sure if people have a preference on that. I also like that we finally get to have the fourth Galylean moon with the second one.

**Comment by rgbkrk** [comment]
I definitely would prefer the pinpoint without the moons.

**Comment by rgbkrk** [comment]
Thanks for these Cameron!

**Comment by takluyver** [comment]
It's a planet getting sucked into a black hole!

I quite like the pinpoint one. I agree that it doesn't say 'planet' much, but the similarity to our regular logo is clear enough.

**Comment by neilpanchal** [comment]
Am I the only one with very strong criticism about the Jupyter logo?

**Comment by ellisonbg** [comment]
Probably not. I personally like it, but I am sure there are some folks that
disllike it. But given the many other design related things we have going
right now, a redesign is most definitely off the table.

On Wed, May 11, 2016 at 4:51 PM, Neil Panchal <notifications@github.com>
wrote:

> Am I the only one with very strong criticism about the Jupyter logo?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/19#issuecomment-218623274>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
Also, Chompy eats people who criticise him :-)
