### ISSUE TITLE
Import Error: No module named 'jupyter_cms'

### ISSUE THREAD

**Issue by AyushKesar** [jupyter/design#27]
I was running 'report_dashboard.ipynb' on cell 4: `%load_ext jupyter_cms` throws an error:
> ImportError: No module named 'jupyter_cms'

I am using conda version 4, python 3.4 on windows 8.1 64-bit.
Also, `conda install jupyter_cms` throws an error:
> package missing in current win-64 channel

**Comment by takluyver** [comment]
Sounds like it's not installed. Install instructions and more info are in this repo:
https://github.com/jupyter-incubator/contentmanagement
