### ISSUE TITLE
Survey existing logo styles

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/design#30]
In developing our brand guide and trademark usage policies, it would be a good idea to understand all of the logo variations we already have. This would include:

* Color variations
* Moon sizes
* Gradient or not.
* Grey colors
* etc.

**Comment by spoorthyv** [comment]
Ive compiled all the logos from Jupyter/Jupyter-Design github, jupyterlab, jupyterhub, jupyter notebooks, and the jupyter.org website. 

Here is the figma: [https://www.figma.com/file/GdH86NHfEjPNVGmdjYfNlaS1/Collection-of-all-existing-Jupyter-Logos](https://www.figma.com/file/GdH86NHfEjPNVGmdjYfNlaS1/Collection-of-all-existing-Jupyter-Logos)

**Comment by merqurio** [comment]
@spoorthyv the link is down 😞 , 404

**Comment by spoorthyv** [comment]
Damn. This should work for now.

![group 2](https://cloud.githubusercontent.com/assets/12418068/17783428/dcf4b932-652c-11e6-952b-b7ff6764a80a.jpg)

**Comment by spoorthyv** [comment]
So far I have noticed 3 main inconsistencies between our logos. 
- Gradient vs no gradient
- Size of planets
- Size of "jupyter" text
- the shade of orange used

**Comment by spoorthyv** [comment]
Further discussion in issues #32
