### ISSUE TITLE
Create brand guide

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/design#31]
This is an issue to track ongoing work by the designers at Cal Poly to create a visual brand guide that documents the visual design and usage aspects of our logo in software, print media, websites, etc. I will let the teams add information about what they are doing.

@jupyter/designers

**Comment by ellisonbg** [comment]
Questions and feedback:

- [ ] Clarification in brand guide about how/where we use Helvetica Nueue.
- [ ] Decisions about logo

**Comment by faricacarroll** [comment]
Summary of Brand Guidelines meeting:

* Changed Jupyter moon colors to all MD greys (500, 600, 700)
* Talked about usage of fonts
    * Third parties do not have to use provided fonts in their content
    * Use Myriad Pro if it is a part of the logo
* Solidify proportion of logos with mathematical ratio
* Determine an alpha level for use of logo as a transparent background
* Provide a lot of different templates for slide deck

**Comment by faricacarroll** [comment]
@spoorthyv @matt-bowers @cameronoelsen 

Here is the visual Jupyter Brand Guide Book that documents the visual design and usage aspects of our logo in software and print media:

[Jupyter Brand Guide Book v6.pdf](https://github.com/jupyter/design/files/581663/Jupyter.Brand.Guide.Book.v6.pdf)

**Comment by cameronoelsen** [comment]
@faricacarroll Looks great! Just one last refinement though that I just saw (that might have been intentional by you, just want to clarify). On the last page of the brand book, the gray box on the bottom with the full jupyter logo at the bottom right seems to stop at the bleed area whereas throughout the rest of the book (such as on the front page and pg 4), the content goes to the edge of each page. Is this intentional?

**Comment by faricacarroll** [comment]
@cameronoelsen We designed it to go to the edge; however, the document bleed settings added the extra white space around it. I've just removed it.

[Jupyter Brand Guide Book v7.pdf](https://github.com/jupyter/design/files/584041/Jupyter.Brand.Guide.Book.v7.pdf)

**Comment by ellisonbg** [comment]
This is in master now so closing this issue. If we have edits to make, let's open new issues. @faricacarroll

**Comment by damianavila** [comment]
This is not closed @ellisonbg :wink: (I guess you forgot to press the button).

**Comment by takluyver** [comment]
Tab-tab-enter used to get you the close and comment button. Now it's Tab-tab-tab-tab-enter, which is much less convenient.
