### ISSUE TITLE
Update R language logo

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/design#41]
the new logo since 2015 can be found here: https://www.r-project.org/logo/

**Comment by cameronoelsen** [comment]
@flying-sheep Where specifically does the logo need to be updated?

**Comment by cameronoelsen** [comment]
cc @ellisonbg @willingc

**Comment by flying-sheep** [comment]
[here](https://github.com/jupyter/design/tree/master/languages). idk why you provide them, but you do

**Comment by willingc** [comment]
@flying-sheep I think that the logos were migrated from an old repo as history. Thanks for the heads up.

@cameronoelsen Your call as to whether to keep or delete the languages folder. If we keep it, let's update the logos to current versions.

Thanks!
