### ISSUE TITLE
JupyterHub Sign In Page

### ISSUE THREAD

**Issue by awantulok** [jupyter/design#5]
Beginning inspiration and mock-ups for JupyterHub sign in page: 
(Screenshots)
![screen-shot-2014-09-15-at-4 08 31-pm](https://cloud.githubusercontent.com/assets/8107694/4583951/94be0d14-4ff6-11e4-9d44-8b353cc9eaee.png)
![screen-shot-2014-09-15-at-4 08 43-pm](https://cloud.githubusercontent.com/assets/8107694/4583952/9612b6c4-4ff6-11e4-8fea-7fe5f4c51abc.png)
![screen-shot-2014-09-15-at-4 09 12-pm](https://cloud.githubusercontent.com/assets/8107694/4583953/97e3d0c8-4ff6-11e4-9eb4-4de5b8c3fa87.png)
![screen-shot-2014-09-15-at-4 11 33-pm](https://cloud.githubusercontent.com/assets/8107694/4583958/9b61ec08-4ff6-11e4-99e1-a8cfe14eb239.png)
(Balsamiq Wireframe)
![sign in page](https://cloud.githubusercontent.com/assets/8107694/4583963/9ee15558-4ff6-11e4-8696-f4e9ca6b629f.png)
(Beginning Antetype Wireframe)
![signin](https://cloud.githubusercontent.com/assets/8107694/4583965/a0e0b0a6-4ff6-11e4-9fc0-dd491684deef.png)

**Comment by Carreau** [comment]
Implemented now !
