### ISSUE TITLE
Do we have Jupyter stickers?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/design#50]
As SciPy / PEARC / JupyterCon are coming up, I wonder if anybody has a stash of stickers sitting around. Anybody know of some?

**Comment by Ruv7** [comment]
Hi there - I am planning on a batch for JupyterCon but I haven't ordered yet. I'm down to my last little pack :( The other options is that I just sent you a link to order those directly from Sticker Mule, this will allow you to order directly. The logo is proofed and already approved but not sure if it makes sense to pay for rush shipping etc. You could also reach out to Stacey at BIDS to see if she has any there...

**Comment by choldgraf** [comment]
thanks @Ruv7 ! I'll look into it and will ask stacey as well!

**Comment by Carreau** [comment]
Look in the lower drawer near my desk in BIDS. In a White envelope likely.
