### ISSUE TITLE
Who made the "community call" logo?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/design#59]
I like the "community call" logo that was done for the youtube videos. Who did that? And would you be willing to do the same for the Jupyter community forum? (basically just replace "community call" with "community forum"?  @tgeorgeux was it you? :-)

**Comment by tgeorgeux** [comment]
Wasn't this closed by the recent PR we had on this? (If not feel free to re-open)

**Comment by choldgraf** [comment]
yep, I figured it out, thanks :-)
