### ISSUE TITLE
Possible notebook design

### ISSUE THREAD

**Issue by Carreau** [jupyter/design#6]
Cf https://github.com/ipython/ipython/issues/6856, Quantopian have made some custom design and we might want to get some things from what they are doing and they would be happy to help.

![img](https://cloud.githubusercontent.com/assets/1588357/4911736/ba62a86c-6492-11e4-914a-3f8d699e8978.png)

**Comment by wikiped** [comment]
Fully appreciating the reasons for grey background in ipython 3.0, I wounder what is the best way to restore the old look of previous version without grey background for those who need to reclaim limited screen space.

**Comment by ellisonbg** [comment]
The geometry of the page hasn't changed any. That area that is now grey
used to be white, but was the same exact size.

On Thu, Mar 5, 2015 at 11:15 PM, wikiped <notifications@github.com> wrote:

> Fully appreciating the reasons for grey background in ipython 3.0, I
> wounder what is the best way to restore the old look of previous version
> without grey background for those who need to reclaim limited screen space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/issues/6#issuecomment-77516917>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by wikiped** [comment]
Geometry (i.e. proportions) might not have changed but what I see on the screen has changed. 
Here is side-by-side of what I see on my screen. I see that new layout takes more space both horizontally and vertically (both screenshots have the same size of 1600 x 370 pixels)

Perhaps I am missing something with regards to the new layout to make it take the same space as before.

![nb2vs3](https://cloud.githubusercontent.com/assets/5990528/6529854/fb1daf1e-c43c-11e4-893c-65d81529cb56.png)

**Comment by Carreau** [comment]
Brian comment was that you will actually not get more space, but anyway . In `custom.css`:
```css
div#notebook {
    background: white;
}

div#notebook-container {
    box-shadow: none;
    // or browser specific -moz -webkit -o prefixes
}
```


![capture d ecran 2015-03-06 a 10 05 15](https://cloud.githubusercontent.com/assets/335567/6530761/966a9612-c3e8-11e4-86a6-6d82440eaefd.png)

**Comment by VelizarVESSELINOV** [comment]
If you can work on minimap (or a quick navigation preview of all the cells) for a long Jupyter page it will be great, there are issues already listed: jupyter/notebook#594
